### ISSUE TITLE
Consider hiding package by default in cabal file

### ISSUE THREAD

**Issue by snoyberg** [nikita-volkov/rerebase#1]
We just ran into a breakage in the Stackage build process which we believe originated with the addition of this package. The (very strange) series of events was:

* We started getting very strange error messages about System.IO not being in scope
* @bergmark tracked it down to https://ghc.haskell.org/trac/ghc/ticket/12509, though we're not using GHCi or -XSafe
* We _are_ using `runghc` to run the `Setup.hs` scripts, so decided to switch to compiling those scripts to executables and running the executables instead
* With that change in place, we get an error about overlapping `Prelude` module names

This is a long way of saying: if you define a `Prelude` module in your package, installing that package will cause a lot of problems for normal usage of tools like `ghc` or `ghci`. Would you consider modifying the cabal file to mark the library as hidden-by-default? This would not have a downside for usage in a project, where the build-depends override any hidden setting on a package.

We've already worked around this in Stackage by marking rerebase as a hidden package.

**Comment by nikita-volkov** [comment]
Good idea! Never knew about that option. Can you please refer to the according Cabal option?

**Comment by snoyberg** [comment]
I don't know where the right docs are, but the relevant bit is:

    exposed: False

Which I stole from http://hackage.haskell.org/package/monads-tf-0.1.0.3/monads-tf.cabal

**Comment by nikita-volkov** [comment]
Thanks! It's rereleased :)

**Comment by ekmett** [comment]
I actually found out about it from asking the cabal folks what to do back when I needed to figure out how to fix said conflict for `monads-tf`.

It is mentioned briefly in https://www.haskell.org/cabal/users-guide/developing-packages.html
but that was the first time I ever used it or saw it used.

**Comment by snoyberg** [comment]
Awesome, thanks for the quick response @nikita-volkov!

And thanks for letting me rip off your cabal file @ekmett 😄

**Comment by nikita-volkov** [comment]
Cheers, guys!
